#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom covr coverage_to_list
#' @importFrom covr file_report
#' @importFrom covr package_coverage
#' @importFrom devtools check
#' @importFrom devtools document
#' @importFrom digest digest
#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr coalesce
#' @importFrom dplyr distinct
#' @importFrom dplyr ends_with
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr lead
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr relocate
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarise
#' @importFrom dplyr transmute
#' @importFrom dplyr where
#' @importFrom fs dir_copy
#' @importFrom fs dir_create
#' @importFrom fs dir_ls
#' @importFrom fs file_copy
#' @importFrom fs file_exists
#' @importFrom fs file_move
#' @importFrom fs file_temp
#' @importFrom fs path
#' @importFrom fs path_dir
#' @importFrom fs path_expand
#' @importFrom fs path_ext_remove
#' @importFrom fs path_ext_set
#' @importFrom fs path_file
#' @importFrom pdftools pdf_text
#' @importFrom pkgdown build_site
#' @importFrom purrr imap_dfr
#' @importFrom purrr keep
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dbl
#' @importFrom purrr map_dfr
#' @importFrom purrr map_int
#' @importFrom purrr map2_lgl
#' @importFrom quarto quarto_render
#' @importFrom readr read_lines
#' @importFrom readr read_rds
#' @importFrom rstudioapi viewer
#' @importFrom stats qnorm
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats weighted.mean
#' @importFrom stringr str_to_sentence
#' @importFrom stringr str_trim
#' @importFrom styler style_pkg
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr unnest
#' @importFrom usethis use_r
#' @importFrom usethis use_test
#' @importFrom usethis use_tidy_description
#' @importFrom utils capture.output
#' @importFrom utils head
#' @importFrom utils tail
#' @importFrom withr with_dir
#' @importFrom yaml read_yaml
## usethis namespace: end
NULL
