tidy_params <- function(
  ...,
  # typesetting params
  draft = TRUE,
  `header-includes` = "",
  title_page = FALSE,
  # layout params
  page_height,
  page_width,
  text_width,
  t_mar,
  i_mar,
  line_count,
  leading = 12,
  ws = 1.001327,
  ws_stretch = 0.552792,
  ws_shrink = 0.921620,
  # h&j params
  parindent = 12,
  parindent_protrusion = 0,
  pretolerance = 100,
  tolerance = 200,
  hfuzz = 0,
  emergencystretch = 0,
  hyphenpenalty = 50,
  exhyphenpenalty = 50,
  doublehyphendemerits = 1e4,
  hyphenate_responded = FALSE,
  # pagination params
  interlinepenalty = 5,
  clubpenalty = 150,
  widowpenalty = 150,
  brokenpenalty = 100,
  reflow_epi_3 = FALSE,
  reflow_epi_5 = FALSE,
  aristotle_space = 0,
  closing_space = 0,
  loose_headings = FALSE,
  ch1pre = 2,
  ch2pre = 1,
  ch3pre = 1,
  ch4pre = 1,
  ch5pre = 1,
  ch6pre = 1,
  ch7pre = 1,
  ch1post = 1,
  ch2post = 1,
  ch3post = 1,
  ch4post = 1,
  ch5post = 1,
  ch6post = 1,
  ch7post = 1
) {
  dots <- list(...)
  if (length(dots) == 1L && is.data.frame(dots[[1]])) {
    if (nrow(dots[[1]]) == 1L) {
      do.call(tidy_params, dots[[1]])
    } else {
      map_dfr(split(dots[[1]], seq(nrow(dots[[1]]))), tidy_params)
    }
  } else {
    tibble(
      draft,
      `header-includes`,
      title_page,
      page_height,
      page_width,
      text_width,
      t_mar,
      i_mar,
      line_count,
      leading,
      ws,
      ws_stretch,
      ws_shrink,
      parindent,
      parindent_protrusion,
      pretolerance,
      tolerance,
      hfuzz,
      emergencystretch,
      hyphenpenalty,
      exhyphenpenalty,
      doublehyphendemerits,
      hyphenate_responded,
      interlinepenalty,
      clubpenalty,
      widowpenalty,
      brokenpenalty,
      reflow_epi_3,
      reflow_epi_5,
      aristotle_space,
      closing_space,
      loose_headings,
      ch1pre,
      ch2pre,
      ch3pre,
      ch4pre,
      ch5pre,
      ch6pre,
      ch7pre,
      ch1post,
      ch2post,
      ch3post,
      ch4post,
      ch5post,
      ch6post,
      ch7post
    )
  }
}
